variant: PyFast

keep:
  # ── application source ─────────────────────────────
  - src/app/__init__.py
  - src/app/main.py
  - src/app/core/
  - src/app/core/**
  - src/app/swagger/
  - src/app/swagger/**
  - src/app/schemas/health.py
  - src/app/services/health.py
  - src/app/services/__init__.py
  - src/app/api/v1/routers/health.py
  - src/app/api/v1/__init__.py
  - src/app/swagger_config/
  - src/app/swagger_config/**


  # ── tests ──────────────────────────────────────────
  - tests/
  - tests/**
  - pytest.ini

  # ── project scripts & metadata ─────────────────────
  - Dockerfile
  - Makefile
  - requirements.txt
  - README.md
  - docker-compose.yml

  # ── IDE / run configs ──────────────────────────────
  - runConfigurations/FastAPI/
  # ── deployment & infra (shared) ────────────────────
  - skaffold.yaml
  - chart/
  - chart/**
  - infra/
  - infra/**

protected:
  - src
  - runConfigurations
  - runConfigurations/FastAPI/FastAPI-Kafka.run.xml


services:
  kafka:
    - runConfigurations/FastAPI/FastAPI-Kafka.run.xml
    - runConfigurations/FastAPI/kafka-up.run.xml
    - src/app/api/v1/routers/kafka.py
    - src/app/schemas/kafka.py
    - src/app/services/kafka/
    - src/app/services/kafka/**
  redis:
    - runConfigurations/FastAPI/Redis.run.xml
    - src/app/services/redis/
    - src/app/services/redis/**
    - src/app/core/redis_client.py

