variant: PyFast

keep:
  # ── application source ─────────────────────────────
  - src/app/
  - src/app/**

  # ── tests ──────────────────────────────────────────
  - tests/
  - tests/**
  - pytest.ini

  # ── project scripts & metadata ─────────────────────
  - Dockerfile
  - Makefile
  - requirements.txt
  - README.md

  # ── IDE / run configs ──────────────────────────────
  - runConfigurations/FastAPI/
  - runConfigurations/FastAPI/FastAPI.run.xml

  # ── deployment & infra (shared) ────────────────────
  - skaffold.yaml
  - chart/
  - chart/**
  - infra/
  - infra/**

protected:
  - src
  - runConfigurations
