variant: PyFast

keep:
  # ── application source ─────────────────────────────
  - src/app/main.py
  - src/app/core/
  - src/app/core/**
  - src/app/swagger/
  - src/app/swagger/**
  - src/app/schemas/health.py
  - src/app/services/health.py
  - src/app/services/__init__.py
  - src/app/api/v1/routers/


  # ── tests ──────────────────────────────────────────
  - tests/
  - tests/**
  - pytest.ini

  # ── project scripts & metadata ─────────────────────
  - Dockerfile
  - Makefile
  - requirements.txt
  - README.md

  # ── IDE / run configs ──────────────────────────────
  - runConfigurations/FastAPI/
  # ── deployment & infra (shared) ────────────────────
  - skaffold.yaml
  - chart/
  - chart/**
  - infra/
  - infra/**

protected:
  - src
  - runConfigurations
  - runConfigurations/FastAPI/FastAPI.run.xml


services:
  kafka:
    - docker-compose.kafka.yml
    - runConfigurations/FastAPI/FastAPI-Kafka.run.xml
    - runConfigurations/FastAPI/MakeBuild.run.xml
    - src/app/api/v1/routers/kafka.py
    - src/app/schemas/kafka.py
    - src/app/services/kafka/
    - src/app/services/kafka/**

